name: mysocialapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  firebase_core: ^1.15.0
  bloc: ^7.0.0
  dio: ^4.0.0
  conditional_builder_rec: ^1.0.0
  flutter_bloc: ^7.0.0
  flutter_conditional_rendering: ^2.0.0
  animated_text_kit: ^4.2.1
  fluttertoast: ^8.0.8
  carousel_slider: ^4.0.0
  shared_preferences: ^2.0.13
  firebase_auth: ^3.3.16
  cloud_firestore: ^3.1.7
  image_picker: ^0.8.4+9
  firebase_storage:
  intl: ^0.17.0
  date_format: ^2.0.5
  shimmer: ^2.0.0
  emoji_picker_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  fonts:
      - family: Jannah
        fonts:
          - asset: assets/fonts/jannah.ttf
            weight: 700
      - family: IconBroken
        fonts:
          - asset: assets/fonts/icons.ttf  # An image asset can refer to one or more resolution-specific "variants", see



